# Generated by Django 5.1.5 on 2025-01-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='properties',
            field=models.ManyToManyField(related_name='appeared_on_search', to='properties.property'),
        ),
    ]
